#!/usr/bin/env bash

source ./task.bash

[[ ${1:-} == -x ]] && { shift; set -x; }

keytask: 'link files'
ok:      '[[ -e $path ]]'
def:     'ln -s $src $path' <<'END'
  [src]=/tmp [path]=$HOME/roottmp
  [src]=/var [path]=$HOME/rootvar
END

summarize
