#!/usr/bin/env bash

main() {
  register systemTypeFunc idSystem
  register hostnameFunc idHost

  system debian
    section system
    task.apt_upgrade
  endsystem

  crostiniDir=/mnt/chromeos/MyFiles/Downloads/crostini

  system crostini
    # copy non-passphrased key if it exists and there isn't already a key
    if [[ -e $crostiniDir/np_id_ed25519.pub ]]; then
      section credential
      task.install 600 $crostiniDir/np_id_ed25519 ~/.ssh/id_ed25519
      task.install 644 $crostiniDir/np_id_ed25519.pub ~/.ssh/id_ed25519.pub
    # copy unique key if it exists and there isn't already a key
    elif [[ -e $crostiniDir/id_ed25519.pub ]]; then
      section credential
      task.install 600 $crostiniDir/id_ed25519 ~/.ssh/id_ed25519
      task.install 644 $crostiniDir/id_ed25519.pub ~/.ssh/id_ed25519.pub
    fi
  endsystem

  section dotfiles
  task.git_clone git@github.com:binaryphile/dotfiles ~/dotfiles
  system macos
    task.ln contexts/macos ~/dotfiles/context
  system crostini
    task.ln contexts/crostini ~/dotfiles/context
  endsystem

  section ssh
  task.ln ~/dotfiles/ssh/config ~/.ssh/config

  section nix
  task.curlpipe_lix_installer
  unstrictly source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  task.ln ~/dotfiles/config.nix ~/.config/nixpkgs/config.nix

  section home-manager
  task.nix-channel_add_home-manager
  task.nix-channel_update
  task.nix-shell_home-manager_install
  unstrictly source ~/.nix-profile/etc/profile.d/hm-session-vars.sh
  task.ln ~/dotfiles/home.nix ~/.config/home-manager/home.nix
  task.home-manager_switch

  system crostini
    section crostini
    task.ln $crostiniDir ~/crostini

    glob $crostiniDir/projects/*        | map target '$target ~/projects/$(basename $target)'       | each task.ln
    glob $crostiniDir/GolandProjects/*  | map target '$target ~/GolandProjects/$(basename $target)' | each task.ln
    glob $crostiniDir/obsidian/*        | map target '$target ~/obsidian/$(basename $target)'       | each task.ln
  endsystem

  section neovim
  task.git_clone git@github.com:binaryphile/dot_vim ~/.config/nvim
  task.curl https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim ~/.local/share/nvim/site/autoload/plug.vim
  task.nvim_headless_PlugInstall

  section tesht
  task.git_clone git@github.com:binaryphile/tesht ~/projects/tesht
  task.git_checkout develop ~/projects/tesht
  task.ln ~/projects/tesht/tesht ~/.local/bin/tesht

  section task.bash
  task.git_clone git@github.com:binaryphile/task.bash ~/projects/task.bash
  task.git_checkout develop ~/projects/task.bash

  section obsidian
  task.git_clone git@bitbucket.org:accelecon/tlilley-daily-notes ~/obsidian/tlilley-daily-notes

  section apps
  each task.ln <<'  END'
    ~/.config                                 ~/config
    ~/.local                                  ~/local
    ~/dotfiles/bash/init.bash                 ~/.bash_profile
    ~/dotfiles/bash/init.bash                 ~/.bashrc
    ~/dotfiles/bash/init.bash                 ~/.profile
    ~/dotfiles/gitconfig                      ~/.gitconfig
    ~/dotfiles/liquidprompt/liquid.theme      ~/.config/liquidprompt/liquid.theme
    ~/dotfiles/liquidprompt/liquidpromptrc    ~/.config/liquidpromptrc
    ~/dotfiles/ranger/rc.conf                 ~/.config/ranger/rc.conf
    ~/dotfiles/ranger/rifle.conf              ~/.config/ranger/rifle.conf
    ~/dotfiles/tmux.conf                      ~/.tmux.conf
  END

  system crostini
    section generate new credential
    [[ -e $crostiniDir/np_id_ed25519.pub ]] && {
      task.remove_matching_file ~/.ssh/id_ed25519.pub $crostiniDir/np_id_ed25519.pub
      task.remove_matching_file ~/.ssh/id_ed25519 $crostiniDir/np_id_ed25519
      rm $crostiniDir/np_id_ed25519{,.pub}
    }
    task.ssh_keygen $crostiniDir/id_ed25519
    task.install 600 $crostiniDir/id_ed25519 ~/.ssh/id_ed25519
    task.install 644 $crostiniDir/id_ed25519.pub ~/.ssh/id_ed25519.pub
  endsystem
}

## helpers

idHost() {
  local filename=/mnt/chromeos/MyFiles/Downloads/crostini/hostname hostname
  [[ $HOSTNAME == penguin && -e $filename ]] && hostname=$(<$filename) || hostname=$HOSTNAME
  echo ${hostname,,}
}

idSystem() {
  [[ $OSTYPE == darwin* ]] && { echo macos; return; }
  echo linux
  [[ $HOSTNAME != penguin ]] || { echo debian; echo crostini; }
}

## task definitions

# system

# task.apt_upgrade upgrades all apt packages to latest.
# It first does an apt update.
task.apt_upgrade() {
  task   'apt update'
  become root
  unchg  'All packages are up to date.'
  def    'apt update'

  task   'apt upgrade'
  prog   on
  become root
  unchg  '0 upgraded, 0 newly installed'
  def    'apt upgrade -y'
}

# nix
task.curlpipe_lix_installer() {
  task   'install single-user nix'
  prog   on
  exist  /nix/var/nix/profiles/default/bin/nix-env
  def    'curl -sSf -L https://install.lix.systems/lix | sh -s -- install linux --no-confirm --init none'

  [[ $OSTYPE == darwin* ]] && local flag=f || local flag=c
  task    'change store ownership to single user'
  become  root
  ok      "[[ $(stat -$flag %u /nix):$(stat -$flag %g /nix) == $(id -u):$(id -g) ]]"
  def     'chown -R $(id -u):$(id -g) /nix'
}

# home manager

task.nix-channel_add_home-manager() {
  task   'add home manager channel'
  exist  ~/.nix-channels
  def    'nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager'
}

task.nix-channel_update() {
  task   'update nix channels'
  prog   on
  exist  ~/.nix-defexpr/channels/home-manager
  def    'nix-channel --update'
}

task.nix-shell_home-manager_install() {
  task   'install home manager'
  prog   on
  exist  ~/.config/home-manager
  def    "nix-shell '<home-manager>' -A install"
}

task.home-manager_switch() {
  task  'apply home manager configuration'
  prog  on
  unchg 'No change so reusing latest profile generation'
  def   'home-manager switch'
}

# neovim
task.nvim_headless_PlugInstall() {
  task  'install neovim plugins'
  exist ~/.local/share/nvim/plugged
  def   'nvim --headless +PlugInstall +qall'
}

# credential

task.install() {
  local mode=$1 src=$2 dst=$3
  task  "copy $src to $dst with mode $mode"
  exist $dst
  def   "install -m $mode $src $dst"
}

task.remove_matching_file() {
  local targetFilename=$1 matchFilename=$2
  task  "remove file $targetFilename if it matches $matchFilename"
  ok    "[[ -e $matchFilename ]] && ! [[ -e $targetFilename ]] || [[ $(<$targetFilename) != $(<$matchFilename) ]]"
  def   "if [[
            -e $matchFilename && -e $targetFilename &&
            \$(<$targetFilename) == \$(<$matchFilename)
          ]]; then
            rm $targetFilename
          fi"
}

task.ssh_keygen() {
  local keyFilename=$1
  task  'generate an ssh key'
  prog  on
  ok    "[[ -e $keyFilename ]]"
  def   "
    read -sp 'generating ssh key.  passphrase: ' passphrase
    read -sp $'\nagain: ' passphrase2
    [[ \$passphrase == \$passphrase2 ]] || { echo -e '\npassphrase did not match'; exit 1; }
    echo
    ssh-keygen -t ed25519 -f $keyFilename -N \"\$passphrase\" -C $USER@$(idHost)
    cat $keyFilename.pub
  "
}

## boilerplate

if [[ -e task.bash ]]; then
  source ./task.bash
else
  lib=$(curl -fsSL https://raw.githubusercontent.com/binaryphile/task.bash/main/task.bash) || exit
  eval "$lib"
  unset -v lib
fi

return 2>/dev/null
set -e

# parse options
while [[ ${1:-} == -?* ]]; do
  case $1 in
    # --help  ) echo "$Usage"  ;;

    -x ) set -x;;

    -s ) shortRun;;

    -- ) shift; break;;
  esac
  shift
done

main
summarize
