#!/usr/bin/env bash

main() {
  # task definitions go here
}

# source task.bash, or download it
if [[ -e task.bash ]]; then
  source ./task.bash
else
#  lib=$(curl -fsSL https://raw.githubusercontent.com/username/reponame/branchname/task.bash) || exit
  eval "$lib"
  unset -v lib
fi

# stop here if sourcing for repl access
return 2>/dev/null
set -e # otherwise turn on exit on error

# enable tracing if given a -x argument
[[ ${1:-} == -x ]] && { shift; set -x; }

main
summarize
